#!/usr/bin/env python3
"""
Validates every Claude Code setting key the baseline cites against the
published settings schema.

The companion to check_nist.py, and the half with sharper consequences. A
wrong NIST identifier embarrasses the document in an assessment; a wrong
setting key silently fails to harden a fleet. Nothing warns you: an
unrecognised key in managed settings is simply not applied.

Three things are checked, in ascending order of what they catch:

  1. The key exists.
  2. The key exists AT THE NESTING the document places it at. A key that
     exists somewhere else in the tree is the error that looks correct in
     review -- `allowManagedHooksOnly` at the top level and
     `permissions.allowManagedHooksOnly` are different settings.
  3. Any value the document pins is in the schema's enum for that key.

What it deliberately does NOT check: whether the pinned value is the right
hardening choice. The schema says `defaultMode` accepts a set of strings;
it does not say which one a security baseline should pick. Same division
as check_nist.py -- existence is machine-checkable, judgment is not.

Validation runs against the key inventory committed at
state/settings-keys.json, so CI needs no network. Regenerate it when
Anthropic ships settings changes:

    python3 automation/check_settings.py --refresh

Exits non-zero with a per-key report on failure. No dependencies.
"""
import argparse
import json
import re
import sys
import urllib.request
from pathlib import Path

ROOT = Path(__file__).resolve().parent
DOCS_DIR = ROOT.parent / "docs"
EXAMPLE = ROOT.parent / "examples" / "managed-settings.json"
INVENTORY = ROOT / "state" / "settings-keys.json"

SCHEMA_URL = "https://www.schemastore.org/claude-code-settings.json"
# Mirrored in SchemaStore's repository; used only if the canonical host is
# unreachable, which it is from some networks.
SCHEMA_MIRROR = (
    "https://raw.githubusercontent.com/SchemaStore/schemastore/master/"
    "src/schemas/json/claude-code-settings.json"
)

USER_AGENT = (
    "Mozilla/5.0 (compatible; claude-enterprise-control-baseline-watcher/1.0; "
    "+https://github.com/ClaySecAI/claude-enterprise-control-baseline)"
)

# A dotted settings key as the baseline writes it: `sandbox.network.allowedDomains`.
# Anchored to a backtick span so prose is not scanned. Rejects anything with a
# space or a slash, which excludes the CI/CD rows in section 4 that are action
# names and CLI flags rather than settings keys.
KEY_SPAN = re.compile(r"`([A-Za-z_][A-Za-z0-9_]*(?:\.[A-Za-z0-9_]+)*)`")


def fetch(url: str) -> dict:
    req = urllib.request.Request(url, headers={"User-Agent": USER_AGENT})
    with urllib.request.urlopen(req, timeout=120) as resp:
        return json.loads(resp.read().decode("utf-8"))


def resolve(node: dict, root: dict, seen: frozenset = frozenset()) -> dict:
    """Follow a local $ref, guarding against a cycle."""
    ref = node.get("$ref")
    if not ref or not ref.startswith("#/"):
        return node
    if ref in seen:
        return {}
    target = root
    for part in ref[2:].split("/"):
        target = target.get(part, {})
        if not isinstance(target, dict):
            return {}
    return resolve(target, root, seen | {ref})


def walk(node: dict, root: dict, prefix: str, out: dict, depth: int = 0) -> None:
    """Collect every dotted key path the schema defines, with its enum."""
    if depth > 12:
        return
    node = resolve(node, root)
    props = node.get("properties")
    if not isinstance(props, dict):
        return
    for name, raw in props.items():
        child = resolve(raw, root) if isinstance(raw, dict) else {}
        path = f"{prefix}.{name}" if prefix else name
        entry = {"type": child.get("type")}
        if isinstance(child.get("enum"), list):
            entry["enum"] = child["enum"]
        out[path] = entry
        walk(child, root, path, out, depth + 1)


def refresh() -> int:
    """Rebuild state/settings-keys.json from the published schema."""
    source = SCHEMA_URL
    try:
        schema = fetch(SCHEMA_URL)
    except Exception as exc:  # noqa: BLE001 -- fall back, but say so
        print(f"canonical host failed ({exc}); trying the SchemaStore mirror")
        schema = fetch(SCHEMA_MIRROR)
        source = SCHEMA_MIRROR

    keys: dict = {}
    walk(schema, schema, "", keys)

    inventory = {
        "_comment": (
            "Generated by automation/check_settings.py --refresh from the published "
            "Claude Code settings schema. Do not hand-edit."
        ),
        "source": source,
        "schema_id": schema.get("$id"),
        "top_level_properties": len(schema.get("properties", {})),
        "total_paths": len(keys),
        "keys": dict(sorted(keys.items())),
    }
    INVENTORY.parent.mkdir(parents=True, exist_ok=True)
    INVENTORY.write_text(json.dumps(inventory, indent=2) + "\n")

    enums = sum(1 for v in keys.values() if "enum" in v)
    print(f"Wrote {INVENTORY.relative_to(ROOT.parent)}")
    print(f"  {inventory['top_level_properties']} top-level properties, "
          f"{len(keys)} total key paths, {enums} with an enum")
    print(f"  source: {source}")
    return 0


def flatten(obj, prefix: str, out: dict) -> None:
    """Flatten a settings document into dotted paths -> value."""
    if isinstance(obj, dict):
        for k, v in obj.items():
            path = f"{prefix}.{k}" if prefix else k
            out[path] = v
            if isinstance(v, dict):
                flatten(v, path, out)


POLICY_BLOCK = re.compile(
    r"## \d+\. Reference `managed-settings\.json`.*?```json\n(.*?)\n```", re.S
)


def policy_drift() -> str | None:
    """The reference policy in the document and examples/ must stay identical."""
    if not EXAMPLE.exists():
        return f"{EXAMPLE.name} is missing"
    for doc in sorted(DOCS_DIR.glob("*.md")):
        m = POLICY_BLOCK.search(doc.read_text())
        if not m:
            continue
        try:
            in_doc = json.loads(m.group(1))
        except json.JSONDecodeError as exc:
            return f"{doc.name}: the reference policy block is not valid JSON ({exc})"
        if in_doc != json.loads(EXAMPLE.read_text()):
            return (
                f"{doc.name}: the reference policy block and {EXAMPLE.name} have "
                "drifted apart; the document states they are identical"
            )
    return None


def check() -> int:
    if not INVENTORY.exists():
        print(f"FAIL inventory missing: {INVENTORY}")
        print("Run: python3 automation/check_settings.py --refresh")
        return 1

    inventory = json.loads(INVENTORY.read_text())
    schema_keys = inventory["keys"]
    # Free-form key spaces: the schema constrains the container, not each child.
    open_prefixes = ("env.", "hooks.", "mcp_servers.", "mcpServers.")

    problems: list[str] = []
    checked = 0

    def known(path: str) -> bool:
        return path in schema_keys or path.startswith(open_prefixes)

    # 1. Keys cited in the prose tables of the baseline.
    for doc in sorted(DOCS_DIR.glob("*.md")):
        for lineno, line in enumerate(doc.read_text().split("\n"), 1):
            if not line.startswith("| 4."):
                continue
            for cand in KEY_SPAN.findall(line):
                # Only treat it as a settings key if its root is a real
                # top-level property; otherwise it is prose in backticks.
                root = cand.split(".")[0]
                if root not in {k.split(".")[0] for k in schema_keys}:
                    continue
                checked += 1
                if not known(cand):
                    near = [k for k in schema_keys if k.endswith("." + cand)
                            or k.split(".")[-1] == cand.split(".")[-1]]
                    hint = f" -- schema has {near[0]!r}" if near else ""
                    problems.append(
                        f"{doc.name}:{lineno}: setting {cand!r} is not at that "
                        f"path in the schema{hint}"
                    )

    # 2. The shipped example policy, key and value.
    if EXAMPLE.exists():
        flat: dict = {}
        flatten(json.loads(EXAMPLE.read_text()), "", flat)
        for path, value in flat.items():
            if path.startswith("$"):
                continue
            checked += 1
            if not known(path):
                problems.append(f"{EXAMPLE.name}: key {path!r} is not in the schema")
                continue
            entry = schema_keys.get(path, {})
            if "enum" in entry and not isinstance(value, (dict, list)):
                if value not in entry["enum"]:
                    problems.append(
                        f"{EXAMPLE.name}: {path} = {value!r} is not in the schema's "
                        f"allowed values {entry['enum']}"
                    )

    # 3. The document asserts its reference policy and the shipped example are
    #    identical. Nothing enforced that, so drift between them would ship an
    #    example that nobody had reviewed against the prose.
    drift = policy_drift()
    if drift:
        problems.append(drift)
    else:
        checked += 1

    for p in problems:
        print(f"FAIL {p}")

    print(f"\nSchema: {inventory['top_level_properties']} top-level properties, "
          f"{inventory['total_paths']} key paths")
    print(f"{checked} cited keys and example values checked, {len(problems)} problems")
    return 1 if problems else 0


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--refresh",
        action="store_true",
        help="re-fetch the published settings schema and rewrite state/settings-keys.json",
    )
    args = parser.parse_args()
    return refresh() if args.refresh else check()


if __name__ == "__main__":
    sys.exit(main())
