#!/usr/bin/env python3
"""
Validates every NIST identifier cited in the baseline against NIST's own
OSCAL catalogs.

Stage 2 writes new SP 800-53 / CSF 2.0 crosswalk mappings unattended, and
check_tables.py only looks at table structure -- it will happily pass a
row citing a control that does not exist. For a document whose whole claim
is that its citations were verified, that is the gap worth closing in CI.

Validation runs against the ID inventory committed at
state/nist-ids.json, so CI needs no network and the result is
deterministic. Regenerate that inventory from NIST's OSCAL catalogs with:

    python3 automation/check_nist.py --refresh

Exits non-zero with a per-identifier report on failure. No dependencies.
"""
import argparse
import json
import re
import sys
import urllib.request
from collections import Counter
from pathlib import Path

ROOT = Path(__file__).resolve().parent
DOCS_DIR = ROOT.parent / "docs"
INVENTORY = ROOT / "state" / "nist-ids.json"

SP800_53_URL = (
    "https://raw.githubusercontent.com/usnistgov/oscal-content/main/"
    "nist.gov/SP800-53/rev5/json/NIST_SP-800-53_rev5_catalog.json"
)
CSF_URL = (
    "https://raw.githubusercontent.com/usnistgov/oscal-content/main/"
    "nist.gov/CSF/v2.0/json/NIST_CSF_v2.0_catalog.json"
)

USER_AGENT = (
    "Mozilla/5.0 (compatible; claude-enterprise-control-baseline-watcher/1.0; "
    "+https://github.com/ClaySecAI/claude-enterprise-control-baseline)"
)

# SP 800-53 control reference: AC-2, AC-2(1), or AC-2j (a statement part).
#
# The leading (?<![.\w]) is load-bearing. Without it this pattern matches the
# tail of every CSF subcategory -- PR.PS-01 yields "PS-01", DE.CM-09 yields
# "CM-09" -- and since PS, CM, IR, RA and SC are all real 800-53 families,
# those phantoms survive the family filter and report as failures.
SP_REF = re.compile(r"(?<![.\w])([A-Z]{2}-\d+)(\(\d+\))?([a-z])?(?![\w(])")

CSF_REF = re.compile(r"\b((?:GV|ID|PR|DE|RS|RC)\.[A-Z]{2}-\d{2})\b")


def fetch(url: str) -> dict:
    req = urllib.request.Request(url, headers={"User-Agent": USER_AGENT})
    with urllib.request.urlopen(req, timeout=120) as resp:
        return json.loads(resp.read().decode("utf-8"))


def walk(control: dict, out: list) -> None:
    out.append(control)
    for child in control.get("controls", []):
        walk(child, out)


def flatten(catalog: dict) -> list:
    out: list = []
    for group in catalog.get("groups", []):
        for control in group.get("controls", []):
            walk(control, out)
    return out


def refresh() -> int:
    """Rebuild state/nist-ids.json from NIST's published OSCAL catalogs."""
    sp = fetch(SP800_53_URL)["catalog"]
    sp_controls = flatten(sp)
    base = [c for c in sp_controls if c.get("class") == "SP800-53"]
    enh = [c for c in sp_controls if c.get("class") == "SP800-53-enhancement"]

    csf = fetch(CSF_URL)["catalog"]
    csf_controls = flatten(csf)
    subs = [c for c in csf_controls if c.get("class") == "subcategory"]
    cats = [c for c in csf_controls if c.get("class") == "category"]

    inventory = {
        "_comment": (
            "Generated by automation/check_nist.py --refresh from NIST's OSCAL "
            "catalogs. Do not hand-edit. Regenerate when NIST publishes a new "
            "release of either catalog."
        ),
        "sp800_53": {
            "source": SP800_53_URL,
            "catalog_version": sp["metadata"].get("version"),
            "families": len(sp.get("groups", [])),
            "base": len(base),
            "enhancements": len(enh),
            "total": len(base) + len(enh),
            "ids": sorted(c["id"].upper() for c in sp_controls),
        },
        "csf_2_0": {
            "source": CSF_URL,
            "catalog_version": csf["metadata"].get("version"),
            "functions": len(csf.get("groups", [])),
            "categories": len(cats),
            "subcategories": len(subs),
            "ids": sorted(c["id"].upper() for c in subs),
        },
    }

    INVENTORY.parent.mkdir(parents=True, exist_ok=True)
    INVENTORY.write_text(json.dumps(inventory, indent=2) + "\n")

    sp_meta, csf_meta = inventory["sp800_53"], inventory["csf_2_0"]
    print(f"Wrote {INVENTORY.relative_to(ROOT.parent)}")
    print(
        f"  SP 800-53 Rev {sp_meta['catalog_version']}: {sp_meta['families']} families, "
        f"{sp_meta['base']} base + {sp_meta['enhancements']} enhancements = {sp_meta['total']}"
    )
    print(
        f"  CSF 2.0 v{csf_meta['catalog_version']}: {csf_meta['functions']} functions, "
        f"{csf_meta['categories']} categories, {csf_meta['subcategories']} subcategories"
    )
    return 0


def oscal_form(family_control: str, enhancement: str | None) -> str:
    """AC-2(1) as written in prose -> ac-2.1 as identified in OSCAL."""
    if enhancement:
        return f"{family_control}.{enhancement.strip('()')}".upper()
    return family_control.upper()


def check() -> int:
    if not INVENTORY.exists():
        print(f"FAIL inventory missing: {INVENTORY}")
        print("Run: python3 automation/check_nist.py --refresh")
        return 1

    inventory = json.loads(INVENTORY.read_text())
    sp_ids = set(inventory["sp800_53"]["ids"])
    csf_ids = set(inventory["csf_2_0"]["ids"])
    families = {i.split("-")[0] for i in sp_ids}

    docs = sorted(DOCS_DIR.glob("*.md"))
    if not docs:
        print(f"FAIL no documents found under {DOCS_DIR}")
        return 1

    problems: list[str] = []
    sp_hits: Counter = Counter()
    csf_hits: Counter = Counter()
    statement_parts: Counter = Counter()

    for doc in docs:
        for lineno, line in enumerate(doc.read_text().split("\n"), 1):
            for control, enhancement, part in SP_REF.findall(line):
                if control.split("-")[0] not in families:
                    continue  # not an 800-53 family prefix; some other identifier
                oscal = oscal_form(control, enhancement)
                written = f"{control}{enhancement}{part}"
                if oscal in sp_ids:
                    sp_hits[written] += 1
                    if part:
                        # AC-2j is a statement part, not a control ID. Valid
                        # notation, but worth surfacing so it stays deliberate.
                        statement_parts[written] += 1
                else:
                    problems.append(
                        f"{doc.name}:{lineno}: SP 800-53 {written!r} "
                        f"does not resolve (looked for {oscal!r})"
                    )

            for sub in CSF_REF.findall(line):
                if sub.upper() in csf_ids:
                    csf_hits[sub] += 1
                else:
                    problems.append(
                        f"{doc.name}:{lineno}: CSF 2.0 {sub!r} is not a subcategory "
                        "in the CSF 2.0 core"
                    )

    for p in problems:
        print(f"FAIL {p}")

    sp_meta, csf_meta = inventory["sp800_53"], inventory["csf_2_0"]
    print(
        f"\nSP 800-53 Rev {sp_meta['catalog_version']}: {len(sp_hits)} distinct IDs, "
        f"{sum(sp_hits.values())} citations"
    )
    print(
        f"CSF 2.0 v{csf_meta['catalog_version']}: {len(csf_hits)} distinct subcategories, "
        f"{sum(csf_hits.values())} citations"
    )
    if statement_parts:
        listed = ", ".join(sorted(statement_parts))
        print(f"Statement-part references (valid, not control IDs): {listed}")
    print(
        f"{len(docs)} document(s) checked against {sp_meta['total']} controls "
        f"and {csf_meta['subcategories']} subcategories, {len(problems)} problems"
    )
    return 1 if problems else 0


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--refresh",
        action="store_true",
        help="re-fetch NIST's OSCAL catalogs and rewrite state/nist-ids.json",
    )
    args = parser.parse_args()
    return refresh() if args.refresh else check()


if __name__ == "__main__":
    sys.exit(main())
